# Generated by Django 4.1.5 on 2023-03-27 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('clas', models.BigIntegerField()),
                ('division', models.CharField(max_length=20)),
                ('roll_no', models.BigIntegerField()),
                ('enrolment_no', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='students_images/')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admn.teacher')),
            ],
        ),
    ]
