# Generated by Django 4.1.5 on 2023-04-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0002_salary_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('notification', models.FileField(upload_to='notifications/')),
                ('date', models.DateField()),
            ],
        ),
    ]
